# Generated by Django 5.1.7 on 2025-03-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descrição', models.TextField()),
                ('data_criação', models.DateTimeField(auto_now_add=True)),
                ('data_conclusão', models.DateTimeField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
            ],
        ),
    ]
