# Generated by Django 5.1.7 on 2025-03-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_django', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='data_conclusão',
            new_name='data_conclusao',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='data_criação',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
